import React, { useEffect, useState } from 'react';
import { Card } from '../../components/ui/Card';
import { StatCard } from '../../components/cards/StatCard';
import { Spinner } from '../../components/ui/Spinner';
import { DollarIcon, TrendingUpIcon, WalletIcon } from '../../components/ui/icons';
import { referralService, ReferralDashboard } from '../../services/referral.service';

export function ReferralEarnings() {
  const [data, setData] = useState<ReferralDashboard | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    referralService.getDashboard().then(setData).finally(() => setIsLoading(false));
  }, []);

  if (isLoading) return <div className="flex justify-center py-12"><Spinner size="lg" /></div>;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Referral Earnings</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Your complete referral earnings
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard label="Available" value={`$${(data?.wallet.availableBalance || 0).toFixed(2)}`} icon={<WalletIcon size={20} className="text-green-600" />} iconBg="bg-green-100 dark:bg-green-900/30" />
        <StatCard label="Pending" value={`$${(data?.wallet.pendingBalance || 0).toFixed(2)}`} icon={<DollarIcon size={20} className="text-yellow-600" />} iconBg="bg-yellow-100 dark:bg-yellow-900/30" />
        <StatCard label="Lifetime" value={`$${(data?.wallet.lifetimeEarned || 0).toFixed(2)}`} icon={<TrendingUpIcon size={20} className="text-primary-600" />} />
      </div>

      <Card>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">How Earnings Work</h3>
        <p className="text-sm text-gray-600 dark:text-gray-400">
          You earn 0.1% of the eligible net trading profit generated by users you refer.
          Rewards are calculated monthly and paid from SignalForge's platform income — never from the referred user's account.
        </p>
      </Card>
    </div>
  );
}