import React from 'react';
import { Card } from '../../components/ui/Card';

export function ReferralTerms() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Referral Terms</h1>
        <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
          Terms and conditions for the referral program
        </p>
      </div>

      <Card>
        <div className="prose prose-sm dark:prose-invert max-w-none space-y-4">
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">1. Reward Rate</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              You earn 0.1% of the eligible net trading profit generated by users you refer.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">2. Funding Source</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Rewards are funded from SignalForge's platform income. They are never deducted from the referred user's trading account.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">3. Eligible Net Profit</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Eligible net profit = gross profit − gross loss − eligible trading costs. Only realized/settled trades count.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">4. Settlement Cycle</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Rewards are calculated and settled monthly, subject to fraud and integrity checks.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">5. KYC Requirement</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              You must complete KYC verification before rewards become withdrawable.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">6. Fraud Prevention</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Self-referrals, duplicate accounts, and manipulated trading volume are prohibited. Violations may result in reward forfeiture.
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}