import React, { useState } from 'react';
import { ChevronDownIcon } from '../../components/ui/icons';

const faqs = [
  { q: 'What is SignalForge AI?', a: 'SignalForge is an enterprise trading intelligence platform that ingests signals from sources like Telegram, uses AI to understand them, applies your risk rules, and executes trades on your MT4/MT5 accounts via MetaApi.' },
  { q: 'Do I need a VPS or EA?', a: 'No. SignalForge uses MetaApi\'s cloud terminal layer, which maintains a persistent connection to your broker on our behalf. No EA, VPS, or local PC is required.' },
  { q: 'Which signal sources are supported?', a: 'Telegram (user session), Discord, WhatsApp, Email, TradingView webhooks, and a REST API for direct provider integration.' },
  { q: 'Is my broker password safe?', a: 'Yes. Your broker credentials are encrypted in transit and at rest, and stored in a dedicated secrets vault. They are never exposed to the frontend.' },
  { q: 'What is KYC and why is it required?', a: 'KYC (Know Your Customer) verifies your identity. It is mandatory before you can subscribe, connect a trading account, or earn referral rewards — this protects the platform and all users from fraud.' },
  { q: 'How does the referral program work?', a: 'You earn 0.1% of the eligible net trading profit generated by users you refer. The reward is funded from SignalForge\'s platform income — never from the referred user\'s account.' },
  { q: 'Can I trade both Demo and Live accounts?', a: 'Yes. You can connect multiple broker accounts (demo and live) and choose which account applies per provider subscription.' },
  { q: 'What happens if a trade is rejected by my broker?', a: 'The rejection reason, broker response, and retry attempts are recorded. You receive a notification with the full reason.' },
];

export function FAQ() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <div className="bg-gray-50 dark:bg-gray-950">
      <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white">FAQ</h1>
          <p className="mt-4 text-lg text-gray-600 dark:text-gray-400">
            Answers to the most common questions.
          </p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <div key={i} className="card">
              <button
                onClick={() => setOpen(open === i ? null : i)}
                className="w-full flex items-center justify-between p-5 text-left"
              >
                <span className="font-semibold text-gray-900 dark:text-white">{faq.q}</span>
                <ChevronDownIcon
                  size={20}
                  className={`text-gray-400 shrink-0 transition-transform ${open === i ? 'rotate-180' : ''}`}
                />
              </button>
              {open === i && (
                <div className="px-5 pb-5 text-sm text-gray-600 dark:text-gray-400">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}