// packages/config/src/roles.ts
import { ALL_PERMISSIONS, PERMISSIONS, Permission } from './permissions';

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  SUPPORT: 'SUPPORT',
  PROVIDER: 'PROVIDER',
  TRADER: 'TRADER',
  USER: 'USER',
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  
  ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROVIDERS,
    PERMISSIONS.MANAGE_REFERRALS,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_BROKERS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_SIGNALS,
    PERMISSIONS.MANAGE_TRADES,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_SYSTEM_HEALTH,
  ],
  
  MODERATOR: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROVIDERS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  
  COMPLIANCE_OFFICER: [
    PERMISSIONS.VIEW_KYC,
    PERMISSIONS.REVIEW_KYC,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_USERS,
  ],
  
  FINANCE_ADMIN: [
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_REFERRALS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
  
  SUPPORT: [
    PERMISSIONS.VIEW_KYC,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  
  PROVIDER: [],
  TRADER: [],
  USER: [],
};

export function getPermissionsForRole(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role: Role, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission);
}