// packages/shared/src/enums/index.ts
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  BANNED = 'BANNED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum AccountType {
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  TRADER = 'TRADER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum Role {
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  TRADER = 'TRADER',
  MODERATOR = 'MODERATOR',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  SUPPORT = 'SUPPORT',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum Permission {
  VIEW_KYC = 'VIEW_KYC',
  REVIEW_KYC = 'REVIEW_KYC',
  APPROVE_KYC = 'APPROVE_KYC',
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_PROVIDERS = 'MANAGE_PROVIDERS',
  MANAGE_REFERRALS = 'MANAGE_REFERRALS',
  MANAGE_PAYMENTS = 'MANAGE_PAYMENTS',
  MANAGE_BROKERS = 'MANAGE_BROKERS',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  MANAGE_SIGNALS = 'MANAGE_SIGNALS',
  MANAGE_TRADES = 'MANAGE_TRADES',
  VIEW_SYSTEM_HEALTH = 'VIEW_SYSTEM_HEALTH',
}

export enum KycStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  GRACE_PERIOD = 'GRACE_PERIOD',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum SubscriptionPlanType {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
  LIFETIME = 'LIFETIME',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SignalSourceType {
  TELEGRAM = 'TELEGRAM',
  DISCORD = 'DISCORD',
  WHATSAPP = 'WHATSAPP',
  TRADINGVIEW = 'TRADINGVIEW',
  REST_API = 'REST_API',
  EMAIL = 'EMAIL',
}

export enum SignalClassification {
  NEW_TRADE = 'NEW_TRADE',
  TRADE_MANAGEMENT = 'TRADE_MANAGEMENT',
  MARKET_ANALYSIS = 'MARKET_ANALYSIS',
  NEWS = 'NEWS',
  EDUCATION = 'EDUCATION',
  ADVERTISEMENT = 'ADVERTISEMENT',
  CONVERSATION = 'CONVERSATION',
  UNKNOWN = 'UNKNOWN',
}

export enum SignalDirection {
  BUY = 'BUY',
  SELL = 'SELL',
}

export enum EntryType {
  MARKET = 'MARKET',
  LIMIT = 'LIMIT',
  STOP = 'STOP',
}

export enum SignalStatus {
  RAW = 'RAW',
  DETECTED = 'DETECTED',
  ANALYZED = 'ANALYZED',
  VALIDATED = 'VALIDATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum TradeStatus {
  PENDING = 'PENDING',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}

export enum TradeEventType {
  SIGNAL_RECEIVED = 'SIGNAL_RECEIVED',
  PARSED = 'PARSED',
  EXECUTION_REQUESTED = 'EXECUTION_REQUESTED',
  EXECUTED = 'EXECUTED',
  SL_MODIFIED = 'SL_MODIFIED',
  TP_MODIFIED = 'TP_MODIFIED',
  BREAK_EVEN = 'BREAK_EVEN',
  TRAILING_STOP = 'TRAILING_STOP',
  PARTIAL_CLOSE = 'PARTIAL_CLOSE',
  MANUAL_CLOSE = 'MANUAL_CLOSE',
  AUTO_CLOSE = 'AUTO_CLOSE',
  PROVIDER_CLOSE = 'PROVIDER_CLOSE',
  RISK_CLOSE = 'RISK_CLOSE',
  STOP_LOSS = 'STOP_LOSS',
  TAKE_PROFIT = 'TAKE_PROFIT',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum TradeEventActor {
  SYSTEM = 'SYSTEM',
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  AUTO_RULE = 'AUTO_RULE',
  BROKER = 'BROKER',
}

export enum BrokerPlatform {
  MT4 = 'MT4',
  MT5 = 'MT5',
}

export enum BrokerAccountType {
  DEMO = 'DEMO',
  LIVE = 'LIVE',
}

export enum BrokerAccountStatus {
  CONNECTED = 'CONNECTED',
  SYNCHRONIZING = 'SYNCHRONIZING',
  DISCONNECTED = 'DISCONNECTED',
  DEPLOYMENT_PENDING = 'DEPLOYMENT_PENDING',
  ERROR = 'ERROR',
}

export enum ReferralRewardStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  SETTLED = 'SETTLED',
  REJECTED = 'REJECTED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  SIGNAL = 'SIGNAL',
  TRADE = 'TRADE',
  KYC = 'KYC',
  REFERRAL = 'REFERRAL',
  PAYMENT = 'PAYMENT',
  SECURITY = 'SECURITY',
  SYSTEM = 'SYSTEM',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
  TELEGRAM = 'TELEGRAM',
  DISCORD = 'DISCORD',
  WEBHOOK = 'WEBHOOK',
}

export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  DEAD = 'DEAD',
}

export enum ProviderCertificationStatus {
  NOT_CERTIFIED = 'NOT_CERTIFIED',
  PENDING = 'PENDING',
  CERTIFIED = 'CERTIFIED',
  REVOKED = 'REVOKED',
}