export enum SignalClassification {
  NEW_TRADE = 'NEW_TRADE',
  TRADE_MANAGEMENT = 'TRADE_MANAGEMENT',
  MARKET_ANALYSIS = 'MARKET_ANALYSIS',
  NEWS = 'NEWS',
  EDUCATION = 'EDUCATION',
  ADVERTISEMENT = 'ADVERTISEMENT',
  CONVERSATION = 'CONVERSATION',
  UNKNOWN = 'UNKNOWN',
}

export enum SignalDirection {
  BUY = 'BUY',
  SELL = 'SELL',
}

export enum SignalStatus {
  RAW = 'RAW',
  DETECTED = 'DETECTED',
  ANALYZED = 'ANALYZED',
  VALIDATED = 'VALIDATED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}