export enum TradeStatus {
  PENDING = 'PENDING',
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}

export enum TradeEventType {
  SIGNAL_RECEIVED = 'SIGNAL_RECEIVED',
  PARSED = 'PARSED',
  EXECUTION_REQUESTED = 'EXECUTION_REQUESTED',
  EXECUTED = 'EXECUTED',
  BREAK_EVEN = 'BREAK_EVEN',
  TRAILING_STOP = 'TRAILING_STOP',
  PARTIAL_CLOSE = 'PARTIAL_CLOSE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum TradeEventActor {
  SYSTEM = 'SYSTEM',
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  AUTO_RULE = 'AUTO_RULE',
  BROKER = 'BROKER',
}