export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  BANNED = 'BANNED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum Role {
  USER = 'USER',
  PROVIDER = 'PROVIDER',
  TRADER = 'TRADER',
  MODERATOR = 'MODERATOR',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  SUPPORT = 'SUPPORT',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}