export const FEATURES = {
  AUTOMATED_TRADING: 'automated_trading',
  MANUAL_TRADING: 'manual_trading',
  SIGNAL_ANALYSIS: 'signal_analysis',
  PROVIDER_MARKETPLACE: 'provider_marketplace',
  TRADER_MARKETPLACE: 'trader_marketplace',
  REFERRAL_PROGRAM: 'referral_program',
  ANALYTICS: 'analytics',
  SIGNAL_REPLAY: 'signal_replay',
  API_ACCESS: 'api_access',
  WHITE_LABEL: 'white_label',
  MULTIPLE_ACCOUNTS: 'multiple_accounts',
  ADVANCED_RISK: 'advanced_risk',
} as const;

export type Feature = typeof FEATURES[keyof typeof FEATURES];

export const FEATURE_BY_PLAN: Record<string, Feature[]> = {
  MONTHLY: [
    FEATURES.AUTOMATED_TRADING,
    FEATURES.MANUAL_TRADING,
    FEATURES.SIGNAL_ANALYSIS,
    FEATURES.PROVIDER_MARKETPLACE,
    FEATURES.REFERRAL_PROGRAM,
    FEATURES.ANALYTICS,
    FEATURES.SIGNAL_REPLAY,
  ],
  YEARLY: [
    FEATURES.AUTOMATED_TRADING,
    FEATURES.MANUAL_TRADING,
    FEATURES.SIGNAL_ANALYSIS,
    FEATURES.PROVIDER_MARKETPLACE,
    FEATURES.TRADER_MARKETPLACE,
    FEATURES.REFERRAL_PROGRAM,
    FEATURES.ANALYTICS,
    FEATURES.SIGNAL_REPLAY,
    FEATURES.MULTIPLE_ACCOUNTS,
    FEATURES.ADVANCED_RISK,
  ],
  LIFETIME: [
    FEATURES.AUTOMATED_TRADING,
    FEATURES.MANUAL_TRADING,
    FEATURES.SIGNAL_ANALYSIS,
    FEATURES.PROVIDER_MARKETPLACE,
    FEATURES.TRADER_MARKETPLACE,
    FEATURES.REFERRAL_PROGRAM,
    FEATURES.ANALYTICS,
    FEATURES.SIGNAL_REPLAY,
    FEATURES.API_ACCESS,
    FEATURES.MULTIPLE_ACCOUNTS,
    FEATURES.ADVANCED_RISK,
  ],
};