export const PERMISSIONS = {
  // User permissions
  VIEW_KYC: 'VIEW_KYC',
  REVIEW_KYC: 'REVIEW_KYC',
  APPROVE_KYC: 'APPROVE_KYC',

  // Management
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PROVIDERS: 'MANAGE_PROVIDERS',
  MANAGE_REFERRALS: 'MANAGE_REFERRALS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  MANAGE_BROKERS: 'MANAGE_BROKERS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  MANAGE_SIGNALS: 'MANAGE_SIGNALS',
  MANAGE_TRADES: 'MANAGE_TRADES',

  // View
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_SYSTEM_HEALTH: 'VIEW_SYSTEM_HEALTH',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROVIDERS,
    PERMISSIONS.MANAGE_REFERRALS,
    PERMISSIONS.MANAGE_PAYMENTS,
    PERMISSIONS.MANAGE_BROKERS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_SIGNALS,
    PERMISSIONS.MANAGE_TRADES,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_SYSTEM_HEALTH,
  ],
  COMPLIANCE_OFFICER: [
    PERMISSIONS.VIEW_KYC,
    PERMISSIONS.REVIEW_KYC,
    PERMISSIONS.APPROVE_KYC,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_USERS,
  ],
  MODERATOR: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PROVIDERS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  USER: [],
};