export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    HOW_IT_WORKS: '/how-it-works',
    FEATURES: '/features',
    PRICING: '/pricing',
    ENTERPRISE: '/enterprise',
    WHITE_LABEL: '/white-label',
    API_PLATFORM: '/api-platform',
    SECURITY: '/security',
    ABOUT: '/about',
    CONTACT: '/contact',
    FAQ: '/faq',
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    EMAIL_VERIFICATION: '/email-verification',
    PHONE_VERIFICATION: '/phone-verification',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    TWO_FACTOR: '/2fa',
    TWO_FACTOR_VERIFY: '/2fa-verify',
  },
  USER: {
    DASHBOARD: '/dashboard',
    SIGNALS: '/signals',
    SIGNAL_SOURCES: '/signal-sources',
    TRADING: '/trading',
    RISK: '/risk',
    BROKERS: '/brokers',
    ANALYTICS: '/analytics',
    MARKETPLACE: '/marketplace',
    REFERRALS: '/referrals',
    SUBSCRIPTIONS: '/subscriptions',
    WALLET: '/wallet',
    SETTINGS: '/settings',
    KYC: '/kyc',
    NOTIFICATIONS: '/notifications',
  },
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    KYC: '/admin/kyc',
    PROVIDERS: '/admin/providers',
    TRADERS: '/admin/traders',
    AUDIT_LOGS: '/admin/audit-logs',
    SECURITY: '/admin/security',
    SETTINGS: '/admin/settings',
  },
  COMPLIANCE: {
    DASHBOARD: '/compliance',
    KYC_QUEUE: '/compliance/kyc-queue',
    DOCUMENT_TYPES: '/compliance/document-types',
    REPORTS: '/compliance/reports',
  },
  EXECUTIVE: {
    DASHBOARD: '/executive',
    SUBSCRIPTION_REVENUE: '/executive/subscription-revenue',
    FINANCIAL_REPORTS: '/executive/financial-reports',
  },
  SUPPORT: {
    HELP_CENTER: '/support',
    TICKETS: '/support/tickets',
    KNOWLEDGE_BASE: '/support/knowledge-base',
  },
} as const;